# Generated by Django 5.0.4 on 2024-05-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Start',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.TimeField()),
                ('group_id', models.BigIntegerField()),
                ('zone', models.TextField(max_length=50)),
                ('task', models.TextField(max_length=200)),
                ('department', models.TextField(max_length=50)),
            ],
        ),
    ]
