# Generated by Django 5.0.4 on 2024-05-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inspection2_0', '0003_remove_start_task_alter_start_zone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idPunkt', models.IntegerField(verbose_name='Пункт')),
                ('Zone', models.TextField(max_length=100, verbose_name='Зона')),
                ('ToDo', models.TextField(max_length=200, verbose_name='Задача')),
                ('link', models.TextField(max_length=200, verbose_name='Картинка')),
                ('H', models.IntegerField(verbose_name='Номер обхода')),
            ],
        ),
    ]
