# Generated by Django 5.0.4 on 2024-05-13 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inspection2_0', '0004_operators'),
    ]

    operations = [
        migrations.CreateModel(
            name='log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('who', models.TextField(max_length=50)),
                ('teleid', models.TextField(max_length=50)),
                ('zone', models.TextField(max_length=50)),
                ('result', models.BooleanField()),
                ('comment', models.TextField(max_length=200)),
                ('punkt', models.IntegerField()),
                ('message_id', models.BigIntegerField()),
                ('department', models.TextField(max_length=100)),
                ('H', models.IntegerField()),
            ],
        ),
    ]
