# Generated by Django 5.0.4 on 2024-05-23 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inspection2_0', '0005_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='Дата')),
                ('userid', models.IntegerField(verbose_name='Айди')),
                ('username', models.TextField(verbose_name='Имя')),
                ('number', models.TextField(verbose_name='Номер телефона')),
                ('department', models.TextField(verbose_name='Отдел')),
            ],
        ),
    ]
