# Generated by Django 5.0.6 on 2024-05-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inspection2_0', '0006_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='operators',
            name='userid',
            field=models.IntegerField(default=0, verbose_name='UserId'),
        ),
    ]
