# Generated by Django 5.0.6 on 2024-05-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inspection2_0', '0007_operators_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operators',
            name='userid',
        ),
        migrations.AlterField(
            model_name='users',
            name='datetime',
            field=models.TimeField(verbose_name='Дата'),
        ),
    ]
