# Generated by Django 5.0.6 on 2024-06-07 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inspection2_0', '0010_admins'),
    ]

    operations = [
        migrations.AddField(
            model_name='admins',
            name='department',
            field=models.IntegerField(default=0, verbose_name='Номер отдела'),
        ),
    ]
