# Generated by Django 5.0.6 on 2024-06-10 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inspection2_0', '0015_admin_animator_cashier_operator_user_waiter_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ['ordering']},
        ),
        migrations.AddField(
            model_name='log',
            name='ordering',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='operator',
            name='ToDo',
            field=models.TextField(max_length=200, verbose_name='Название задачи'),
        ),
        migrations.AlterField(
            model_name='operator',
            name='idPunkt',
            field=models.IntegerField(verbose_name='Чек номер'),
        ),
        migrations.AlterField(
            model_name='operator',
            name='link',
            field=models.TextField(max_length=200, verbose_name='Ссылка на изображение'),
        ),
    ]
