# Generated by Django 5.0.6 on 2024-06-10 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inspection2_0', '0017_alter_log_options_remove_log_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='department',
            field=models.CharField(default='operator', max_length=50),
        ),
        migrations.AlterField(
            model_name='admin',
            name='department',
            field=models.CharField(default='admin', max_length=50),
        ),
    ]
