# Generated by Django 5.0.4 on 2024-06-27 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inspection2_0', '0018_operator_department_alter_admin_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin',
            field=models.BooleanField(default=False, verbose_name='Администратор'),
        ),
    ]
